import json
from web3 import Web3

ganache_url="http://127.0.0.1:7545"
web3=Web3(Web3.HTTPProvider(ganache_url))
#0x0D741328f73894EAC1531424041533906F65FD55
#abi=json.loads('[{"inputs":[],"stateMutability":"nonpayable","type":"constructor"},{"inputs":[{"internalType":"string","name":"_nombrePersona","type":"string"},{"internalType":"uint256","name":"_edadPersona","type":"uint256"},{"internalType":"string","name":"_idPersona","type":"string"}],"name":"Representar","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"VerResultado","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"string","name":"_candidato","type":"string"}],"name":"VerVotos","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"string","name":"_candidato","type":"string"}],"name":"Votar","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"string","name":"_mail","type":"string"},{"internalType":"string","name":"_pass","type":"string"}],"name":"login","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"owner","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"verCAndidatos","outputs":[{"internalType":"string[]","name":"","type":"string[]"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"string","name":"_mail","type":"string"},{"internalType":"string","name":"_pass","type":"string"}],"name":"verifi","outputs":[],"stateMutability":"nonpayable","type":"function"}]')
abi=json.loads('[{"inputs":[],"stateMutability":"nonpayable","type":"constructor"},{"inputs":[],"name":"imprimir","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"string","name":"_mail","type":"string"},{"internalType":"string","name":"_pass","type":"string"}],"name":"log","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"owner","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"string","name":"_mail","type":"string"},{"internalType":"string","name":"_pass","type":"string"}],"name":"verifi","outputs":[],"stateMutability":"nonpayable","type":"function"}]');

#var loginContract = new web3.eth.Contract([{"inputs":[],"stateMutability":"nonpayable","type":"constructor"},{"inputs":[],"name":"imprimir","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"string","name":"_mail","type":"string"},{"internalType":"string","name":"_pass","type":"string"}],"name":"log","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"owner","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"string","name":"_mail","type":"string"},{"internalType":"string","name":"_pass","type":"string"}],"name":"verifi","outputs":[],"stateMutability":"nonpayable","type":"function"}]);
#direccion del contraro deployed
address=web3.toChecksumAddress("0xC74a397228E1510B3AB38BE12b10f648C86dbded")
#var votacionContract = new web3.eth.Contract([{"inputs":[],"stateMutability":"nonpayable","type":"constructor"},{"inputs":[{"internalType":"string","name":"_nombrePersona","type":"string"},{"internalType":"uint256","name":"_edadPersona","type":"uint256"},{"internalType":"string","name":"_idPersona","type":"string"}],"name":"Representar","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"VerResultado","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"string","name":"_candidato","type":"string"}],"name":"VerVotos","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"string","name":"_candidato","type":"string"}],"name":"Votar","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"string","name":"_mail","type":"string"},{"internalType":"string","name":"_pass","type":"string"}],"name":"login","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"owner","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"verCAndidatos","outputs":[{"internalType":"string[]","name":"","type":"string[]"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"string","name":"_mail","type":"string"},{"internalType":"string","name":"_pass","type":"string"}],"name":"verifi","outputs":[],"stateMutability":"nonpayable","type":"function"}]);
contract=web3.eth.contract(address=address,abi=abi)

print(contract.functions.imprimir().call())
